return {
  -- tools
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "alex",
        "ansible-language-server",
        "astro-language-server",
        "bash-language-server",
        "black",
        "clangd",
        "codelldb",
        "copilot-language-server",
        "css-lsp",
        "delve",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "erb-lint",
        "eslint-lsp",
        "eslint_d",
        "flake8",
        "gofumpt",
        "goimports",
        "golangci-lint",
        "golangci-lint-langserver",
        "gomodifytags",
        "gopls",
        "hadolint",
        "html-lsp",
        "impl",
        "intelephense",
        "isort",
        "js-debug-adapter",
        "json-lsp",
        "kotlin-language-server",
        "lua-language-server",
        "luacheck",
        "markdown-toc",
        "markdownlint",
        "markdownlint-cli2",
        "marksman",
        "prettier",
        "prettierd",
        "proselint",
        "pyright",
        "rust-analyzer",
        "selene",
        "shellcheck",
        "shfmt",
        "solargraph",
        "sqlfluff",
        "sqlls",
        "stylua",
        "svelte-language-server",
        "tailwindcss-language-server",
        "taplo",
        "terraform-ls",
        "tflint",
        "typescript-language-server",
        "vim-language-server",
        "vtsls",
        "write-good",
        "yaml-language-server",
        "yamlfmt",
        "yamllint",
      },
    },
  },

  -- lsp servers
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        ["*"] = {
          keys = {
            { "<leader>f", "<cmd>lua require('conform').format()<CR>", has = "format", desc = "Format" },
          },
        },
      },
    },
  },
}
